### ISSUE TITLE
Trouble running on Alpine Linux

### ISSUE THREAD

**Issue by johnstt** [deurk/mvdsv#10]
Hi!
I'm trying to run mvdsv on Alpine Linux (from [this ](https://hub.docker.com/_/alpine/)docker container), and I get this error:

```
VM_Load: "qwprogs"
ERROR: SV_Error: PR1_LoadProgs: couldn't load progs.dat
```

I tried this with mvdsv from the nquake package ( https://github.com/nQuake/server-linux/raw/master/releases/nquakesv_installer-linux-latest.tar.gz ), and also with a fresh build from this repo. 

Outside of my mvdsv binary, I'm using all the files installed from the nquake Linux server installer script (so my qwprogs.so is the same). 

I've set up and run nquake servers on Ubuntu and Fedora before, so this is unlikely to be user error.
Any ideas what could be going wrong? I'm not sure if anyone has tried on Alpine before...

**Comment by meag** [comment]
Don't have an obvious solution to this, but check that `/sv_progtype 1` is set (if ktx is in compiled qwprogs.so format) and that that game directory is set correctly on startup (`-game ktx`).  But you say that you're using all nquake configurations so it seems unlikely that either wouldn't be set correctly.

**Comment by johnstt** [comment]
Is it worth a try rebuilding qwprogs from the ktx source?

I tried that too but I was getting blocked by some gcc error so I figured I need a good night's sleep before continuing...

**Comment by johnstt** [comment]
I just got it to work by editing ktx a little bit and building qwprogs.so from it.
The changes were just around some strlcat/strlcpy uses to match the string.h that comes with Alpine's build tools (const char* src instead of char*).

I'll play around with this server a bit and see if it blows up. If not, I can submit a pull at some point..

**Comment by lasselehtinen** [comment]
I have this same issue. Freshly compiled mvdsv+ktx and also the precompiled nQuake Linux server version have the same issue. I am running this on the Amazon Linux AMI.

```
[root@ip-xxx quakeworld]# ./mvdsv -port 27510 -game ktx
============= Starting MVDSV =============
32.0 megabyte heap
QuakeWorld Initialized
MVDSV 0.31, (build 0) (Linux)
Build date: Aug  7 2016, 19:44:53
MVDSV Project home page: https://github.com/deurk/mvdsv

couldn't exec server.cfg
Can't find maps/mvdsv-kg.bsp
VM_Load: "qwprogs"
ERROR: SV_Error: PR1_LoadProgs: couldn't load progs.dat
```

**Comment by johnstt** [comment]
(I'm not familiar with Amazon Linux, so some of this might not apply. Hopefully it is helpful, though)

You compiled an mvdsv binary and a qwprogs binary? Was qwprogs **.so** or **.dat**? 

As meag mentioned, you'll need **sv_progtype 1** for mvdsv to load the .so (instead of .dat). One of the default configs in the nquakesv package does this, but you can just add it anywhere and +exec that cfg file with your ./mvdsv line.

Did you build ktx with glibc? I still need to look over my ktx changes (to build with musl-libc) and figure out why I get the weird behaviour after matches.

**Comment by lasselehtinen** [comment]
Seems like sv_progtype 1 did the trick for me. I did not actually finish any matches yet but I will test it at some point.

**Comment by johnstt** [comment]
I just got it all to run without rebuilding any code using [this](https://hub.docker.com/r/frolvlad/alpine-glibc/). 

It sorta defeats the purpose of Alpine Linux (by using glibc)... but I still get a really simple container with a qw server running. I'll close this for now. Cheers!
