### ISSUE TITLE
can't see spectators talk all of the time

### ISSUE THREAD

**Issue by ciscon** [deurk/mvdsv#11]
as a normal player you cannot always see spectators talk.  if two players are in a game, one goes spectator, and then says something, the actual player will not see it.  on the spectator's screen they will see their message and it will be prefaced with "spec".  if the other player is to then go spectator, they will see eachother's messages and they will no longer be prefaced with "spec".  if one of those players is to then go back to non-spectator, they will see eachother's messages and neither will be prefaced as "spec" even though one of the players is a spectator.

**Comment by jite** [comment]
Hmm, I think there might some other things involved here:

1) Are you sure you're using /say and not /say_team (cause /say_team as
spectator will only send messages to spectators if you are a spectator
yourself)

2) Most servers won't allow spectalk during games, meaning that if a game
is on and you're spectating, your messages will only be seen by other
spectators.

2016-08-29 19:31 GMT+02:00 dustin <notifications@github.com>:

**Comment by ciscon** [comment]
1) yes, to test i'm using /say
2) i haven't specifically disabled spectator talking, is there a variable that i could check?
2a) the only thing i could find that might cause this would be serverinfo fpd, though it's always been set to 206 and i've never encountered this problem before.  as a side note, even if i do not set fpd anywhere it defaults to 206 and it appears i can't override this.  the only way i can is to do it via rcon while the server is running, and upon map change it defaults back to 206 even though the only places it is set is in mvdsv.cfg, where it is set to another value.

**Comment by meag** [comment]
Check the value of `sv_spectalk`, though the mod can override the default behaviour.

**Comment by ciscon** [comment]
it is set to 1 (running ktx 1.37 btw, though the only code update in quite some time was just a version bump).  i managed to get fpd to something other than 206, either 64 or 142 - neither of which appear to fix the problem.

**Comment by meag** [comment]
`k_spectalk`?  You should be able to toggle with `/silence`

Is this during the game or during prewar?

**Comment by ciscon** [comment]
k_spectalk is 0, i'm assuming this should be 1?
it's an ffa/matchless server

**Comment by meag** [comment]
Yes, looks like that needs to be set to 1 in /configs/usermodes/matchless/default.cfg or /configs/usermodes/ffa/default.cfg, depending on if `k_use_matchless_dir` is set (nothing is easy)

**Comment by ciscon** [comment]
that was definitely it, apparently having it set in my ktx.cfg isn't sufficient.  thanks for the help, i apologize for the bogus bug.

**Comment by meag** [comment]
No problem (closing)
