### ISSUE TITLE
binaries with missing source

### ISSUE THREAD

**Issue by leegarrett** [deurk/mvdsv#12]
Hi,

I'm planning on packaging mvdsv for Debian, and while reviewing the source tree I noticed that there are two binaries checked into the git repo:

- tools/ml/build/x86/ml.exe
- tools/gas2masm/build/x86/gas2masm.exe

While it seems that the latter can be built on Windows from the source (I haven't tested it), the former has no clear function or accompanying source. If that was the case it wouldn't be shippable in Debian. Can you tell me about the function of ml.exe? If it's just an artifact from cleaning up the repo, could you remove it from the next release?

**Comment by deurk** [comment]
Great, we were just talking about that on Discord last night, having .deb and .rpm for mvdsv, ktx and so on.

I think I recall ML as been the Microsoft linker for assembly-language source files. It should probably be removed altogether and just appear in compilation howto IMO.

A review of the repository is going to take place soon I think to make it as clean and slim as possible.

**Comment by meag** [comment]
@VVD do you have any objection to removing all the assembler for Windows builds?  Would let us clear this kind of thing up

**Comment by leegarrett** [comment]
This got fixed in pull request #23 from fzwoch/binary_tools. Closing now. Thanks to everyone involved!
