### ISSUE TITLE
Issue spectating a passworded server

### ISSUE THREAD

**Issue by mushis** [deurk/mvdsv#49]
when a server has a password there are some problems regarding the ability to spectate.

ok, the server is passworded, the first thing to do is to set the /password and/or /spectator_password right?? ok, done, on both.

but:
- /observe doesn't work as intended
- spectator 1 and /reconnect doesn't work. 

my guess is that /spectator_password isn't doing what it is supposed to do.

-- start of mambo jambo --
The only way to spectate a FULL server with password is doing it like this, around the problem (doesn't work when the server isn't full):
- set password
- spectator 0  (yes, zero)
- reconnect - it will try to connect as player. if the server is full (maxplayers), it will connect you as spectator instead! tada!! 

-- end of mambo jambo --

also, spectator_password is being saved on the config. i guess password as well? is this ok?

Example server: fr.predze.dk:28503
i can give you pass on discord

**Comment by meag** [comment]
`/spectator <password>` is how the client sets a spectator password
`/spectator_password <password>` is the server-side version

Understand the confusion, as `/password` is both

**Comment by ptdev** [comment]
Hi, hate to revisit a closed topic but I'm also having this exact issue, down to the steps needed to work around it.

You mention that we set the spectator password by using /spectator <password> but afaik the /spectator command has always been a boolean 0 or 1 if one wishes to join as player or spectator (and not as a way to set the spectator password?).

If this has been changed, then the help text for the /spectator cmd needs to be fixed and have this clarified.

**Comment by meag** [comment]
Hi @ptdev 

I think it has always been this way (https://github.com/id-Software/Quake/blob/bf4ac424ce754894ac8f1dae6a3981954bc9852d/QW/server/sv_main.c#L552-L567 for `spectator 0` being a special case in the originally release sourcecode, with `spectator <anything else>` allowing a connection to a server with blank `spectator_password` or `spectator_password none`).

Agree with you about the documentation in the clients.

Thanks,
