### ISSUE TITLE
compiling / running on x64_86

### ISSUE THREAD

**Issue by Bonuspunkt** [deurk/mvdsv#5]
i build the executable on a fresh ubuntu 14.04.4 and when i tried to run mvdsv i got

```
ERROR: SV_Error: PR_ExecuteProgram: NULL function
```

after googling i found you had to pass a param to make

```
make FORCE32BITFLAGS=-m32
```

the compile threw errors but

```
apt-get install gcc-multilib
```

fixed it

**Comment by angeld29** [comment]
mod used server function not exists in mvdsv, maybe some extension from other server

**Comment by deurk** [comment]
Compile fines with current build automation.
